# Generated by Django 4.1.2 on 2023-03-04 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='follow',
            new_name='follower',
        ),
    ]
