# Generated by Django 4.1.2 on 2023-03-04 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_rename_follow_follow_follower'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='follower',
            new_name='following',
        ),
    ]
