# Generated by Django 4.1.2 on 2023-03-06 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_alter_follow_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='user',
            new_name='follower',
        ),
    ]
